### ISSUE TITLE
Add image ID from "Dynamic Data" - Add Dynamic image when using the Media Library option, allowing for dynamic images to use srcset

### ISSUE THREAD

**Issue by asbpette** [soflyy/oxygen-bugs-and-features#107]
I want to be able to insert dynamic data to image ID.

I know it is possible to do this when inserting to the image Url, but i really like the srcset feature when inserting from media library, and would like to be able to insert the attachment id, directly from dynamic data

![skjermbilde 2019-02-26 11 02 41](https://user-images.githubusercontent.com/2612612/53404583-4373bb80-39b6-11e9-838a-62bcb1b7bec6.png)

**Comment by shoelaced** [comment]
+1 for this.

**Comment by davidlower8** [comment]
+1 - essential.

**Comment by driesrengle** [comment]
+1! really really need this!

**Comment by marcellocurto** [comment]
+1
Didn't even realize this was missing until I looked at the source code and wondered where all the srcset attributes went.
My current workaround is a reusable part that calls the_post_thumbnail.

**Comment by MorbidNorth** [comment]
+1 Feels like a no brainer.

**Comment by LoicDelahais** [comment]
+1

**Comment by Martin-1** [comment]
+1

**Comment by thomasjulienalain** [comment]
+1

**Comment by katsar0v** [comment]
+1 - https://github.com/soflyy/oxygen-bugs-and-features/issues/1746

**Comment by thomasjulienalain** [comment]
+1 !

**Comment by SZeimke** [comment]
+1

**Comment by grampa** [comment]
+1

**Comment by acicovic** [comment]
For those who haven't, please vote for this with the thumbs up icon in the first post of the thread. This is how the Oxygen team can see the popularity of a request using sorting in Github. Using +1 posts most probably won't have any effect.

Thanks.

**Comment by Computerbuddha** [comment]
+1

**Comment by yoshi-12321** [comment]
+1

**Comment by goninski** [comment]
absolutely needed - btw I think the title of this topic isn't correct and could lead to lower votings. From my point of view the image ID doesn't matter. The only importance is the scrset/sizes-Attribute!

**Comment by wacaszafar** [comment]
@marcellocurto 

Can you share the method or code block / snippet you used to make it work please. Thank you.

**Comment by marcellocurto** [comment]
@wacaszafar

If I remember correctly I solved it by creating a reusable part that contains just a code block with the following code:

`<?php echo get_the_post_thumbnail(null, 'large', ['class' => 'ct-image']); ?>`

That will output the featured image the regular WordPress way.

However, the code block quickly became too limiting, since I didn't always need just the featured image.
It doesn't seem to be possible to pass arguments to reusable parts, so I added a new code block for each image that wasn't a featured image with the following code:

`<?php echo wp_get_attachment_image($attachment_id, 'large', false, ['class' => 'ct-image']); ?>`

Alas that approach became too annoying and I started to offload more logic into a separate plugin to call those functions inside Oxygen templates.
At that point it no longer made sense to use Oxygen and I went back to writing themes from scratch again.

**Comment by jamescrabb** [comment]
definite must have please

**Comment by JulieCardinale** [comment]
+1

**Comment by dsgnrdev** [comment]
+1

**Comment by Hud1ai2** [comment]
+1

**Comment by ali3412** [comment]
+1

**Comment by vadimbk** [comment]
+100500

**Comment by jamescrabb** [comment]
Just needs to be done.....

**Comment by martinleejd** [comment]
+1 - man, it's killing my seo site speed just having the image url. not good - anyone got a work around?

**Comment by heavestudio** [comment]
+10

**Comment by antic1pate** [comment]
+1

**Comment by Mozzarellathicc** [comment]
+1

**Comment by kenanmalas** [comment]
+1

**Comment by fmommeja** [comment]
Please! +1

**Comment by KonradDeskiewicz** [comment]
I'm quite new to Oxy (one or two small projects) and as I hit the e-commerce and "product image" then it struck me - no srcset for those pictures! Why?! Oh, why? Definitely +1

**Comment by jonathan-cfmp** [comment]
+1

**Comment by annettePixie** [comment]
New to oxygen and suprised by this - yep +1

**Comment by unomark** [comment]
Would be so great if this was fixed! +1

**Comment by katsar0v** [comment]
Any updates on this feature @Spellhammer @KittenCodes ? Would be great to see it in oxygen 4

**Comment by cvladan** [comment]
OMG :(

**Comment by AndyFlight21** [comment]
Found this which seems to work great, the only workflow change is using a code block instead of a image element. Needed this functionality for a template which dynamically changes my service page images.

(https://www.awesomeacf.com/responsive-images-wordpress-acf/)

**Comment by CameronGilroy** [comment]
+1

**Comment by shibupandit** [comment]
+1

**Comment by loiceoka** [comment]
Yes for this too! +1

**Comment by uhlhosting** [comment]
Oxygen team needs to prioritise better important updates, since 2019 its a bit too much to wait for features that are critical in some developments.

**Comment by ribenawrath** [comment]
This issue has a lot in common with the Gutenberg one here

https://github.com/soflyy/oxygen-bugs-and-features/issues/1223?fbclid=IwAR3V9tgC3pRArF-49JJyubisvQWCA6m1xJ-hSr8ksGnWYLkvrHe8Ap92hGE

**Comment by Spellhammer** [comment]
Added in 4.0, which is currently in beta 2.

**Comment by philthebass** [comment]
+1 for this please

**Comment by shoelaced** [comment]
I'm working on a site with O2 4.0 and weirdly, the ACF option is available in the dynamic data for the image URL, but not in the new dynamic data option for the image ID. Is this intended for some reason?

**Comment by popomomo** [comment]
> 

Same here

**Comment by schmekism** [comment]
+1   Is this closed because it was resolved?

**Comment by 0Kangaxx0** [comment]
> +1 Didn't even realize this was missing until I looked at the source code and wondered where all the srcset attributes went. My current workaround is a reusable part that calls the_post_thumbnail.

Can you be a bit more specific on this.
I am looking for a workaround.

**Comment by marcellocurto** [comment]
@0Kangaxx0, that's how I used to do it:

> @wacaszafar
> 
> If I remember correctly I solved it by creating a reusable part that contains just a code block with the following code:
> 
> `<?php echo get_the_post_thumbnail(null, 'large', ['class' => 'ct-image']); ?>`
> 
> That will output the featured image the regular WordPress way.
> 
> However, the code block quickly became too limiting, since I didn't always need just the featured image. It doesn't seem to be possible to pass arguments to reusable parts, so I added a new code block for each image that wasn't a featured image with the following code:
> 
> `<?php echo wp_get_attachment_image($attachment_id, 'large', false, ['class' => 'ct-image']); ?>`
> 
> Alas that approach became too annoying and I started to offload more logic into a separate plugin to call those functions inside Oxygen templates. At that point it no longer made sense to use Oxygen and I went back to writing themes from scratch again.

**Comment by 0Kangaxx0** [comment]
> @0Kangaxx0, that's how I used to do it:
> 
> > @wacaszafar
> > If I remember correctly I solved it by creating a reusable part that contains just a code block with the following code:
> > `<?php echo get_the_post_thumbnail(null, 'large', ['class' => 'ct-image']); ?>`
> > That will output the featured image the regular WordPress way.
> > However, the code block quickly became too limiting, since I didn't always need just the featured image. It doesn't seem to be possible to pass arguments to reusable parts, so I added a new code block for each image that wasn't a featured image with the following code:
> > `<?php echo wp_get_attachment_image($attachment_id, 'large', false, ['class' => 'ct-image']); ?>`
> > Alas that approach became too annoying and I started to offload more logic into a separate plugin to call those functions inside Oxygen templates. At that point it no longer made sense to use Oxygen and I went back to writing themes from scratch again.

Thanks for your reply :)
Sorry for my following noob questions ;) I new to wordpress and oxygen.
As far as I understand your approach you use the following line to "grap" the featured image.
`<?php echo get_the_post_thumbnail(null, 'large', ['class' => 'ct-image']); ?>`
But how do you add that "grapped" image into a oxygen gallery, which comes after the code block I assume?

**Comment by marcellocurto** [comment]
@0Kangaxx0 no problem.
I'm sorry, but I don't know. I never used the Oxygen gallery. The code above is just to display a single image.
I don't even know why this is not solved. All I wanted was responsive images in ```srcset``` which comes as a default with ```wp_get_attachment_image``` and ```get_the_post_thumbnail```.

**Comment by monhelle** [comment]
+1 

I have tried adding an image url to the ACF fields and using this url in the dynamic image url field, but still wont show
