### ISSUE TITLE
Dynamic Data: Date "Format" is not respected

### ISSUE THREAD

**Issue by ddenev** [soflyy/oxygen-bugs-and-features#489]
**Describe the bug**
The "Format" parameter for the Date dynamic data field does not have any effect.

**To Reproduce**
1. Add a dynamic data for a text field and make the dynamic data show the date of the post
2. When Oxygen asks for "Format" enter any format that is different from the default one in WordPress
3. Visualize the page

**What actually happens**
The default date format is shown, no matter what format you specify.

Oxygen v2.4.1

The bug is due to:
In the **component-framework\includes\oxygen-dynamic-shortcodes.php** file, on line 240, the function `get_the_date()` is called without the `$format` argument.

**Comment by drank** [comment]
Could you please include this fix in the new 3.1 bugfix release? It's a 30 seconds fix, really :)

**Comment by drank** [comment]
Still not fixed in 3.1RC1.
Now the line to fix in **component-framework\includes\oxygen-dynamic-shortcodes.php** is 272.

**Comment by Morosko** [comment]
This is a crucial feature for me with such an easy fix. Please include it in the next update.

**Comment by Netzlichter** [comment]
Still not fixed in Version 3.4 RC 2

**Comment by quentin-bettoum** [comment]
Having this issue in 3.6.1
Would be awesome if you could include this fix in the next update. It's an important feature, I fixed it locally for now.

**Comment by SvenWoltmann** [comment]
I also have this problem in 3.6.1.
It's so super-easy to fix (takes 10 seconds), please include this in the next update.

**Comment by Deralict** [comment]
+1

**Comment by techjase** [comment]
+1

**Comment by yankiara** [comment]
I can't believe this is still not fixed.
This dev team is really useless...

**Comment by WilliamVercken** [comment]
Same bug here, 2 years and still no fix?

**Comment by Nelmedia** [comment]
This type of thing is one of the reasons I haven't switched to Oxygen yet... And people complain when it takes few days to the Elementor team to answer...

**Comment by shmaltz** [comment]
I guess they're waiting for the v4.0 Vue rewrite to fix this...

**Comment by BrynWithin** [comment]
I'd really like to see this get fixed. Such a tiny bug can cause so much frustration.

**Comment by Paciente8159** [comment]
Lol. Bumped into this in version 3.6.1. Took a look at the code and confirmed that this is still in version 3.7.
Super easy fix.
Just add the $format argument inside the get_the_date function call in line 273 of oxygen-dynamic-shortcodes.php file.

**Comment by viniciusmartin** [comment]
+1

**Comment by viniciusmartin** [comment]
3.8.1 and not has fixed...

**Comment by pauldyke** [comment]
Please fix. Thank you.

**Comment by nickfmc** [comment]
@pauldyke you cleaver SOB!! didn't know about that function. I just wanted a dynamic date for my sites copyrights, great workaround! however WOW on this ticket being open still, haha

**Comment by djhaystack** [comment]
Silly this is still open. Basically wasted days recreating a site in Oxygen to make it cleaner and leaner, and I can't make my Events Calendar events display the way I wish due to this.

**Comment by nickfmc** [comment]
@djhaystack did you try out what @pauldyke suggested using [oxygen data='phpfunction' function='get_the_date' arguments='F Y']

**Comment by djhaystack** [comment]
@nickfmc I did. In my case it's [oxygen data='phpfunction' function='tribe_get_start_date' arguments='F Y'] as I'm trying to pull the start datetime from The Events Calendar. I'm sure there's a way to make this work that I'm missing, but I'm no coder obviously. I did find that tribe_get_start_date is the function for it, but there may be more needed to make this work.

**Comment by nickfmc** [comment]
well then @djhaystack this is totally different function and issue that is stated in this topic because that's not what dynamic date is for, so you are probably best asking your question on something like the facebook group, however it's most likely not working because you are not passing the correct function arguments for your specific function.   you would need something more like 
arguments='null, false, "F j, Y - g:i a"'  refer to the documentation of the function.  https://docs.theeventscalendar.com/reference/functions/tribe_get_start_date/

**Comment by KittenCodes** [comment]
Fixed in v3.8 Beta 1.

**Comment by DemonioCZ** [comment]
Just updated to 3.8 and fixed
