### ISSUE TITLE
MULTIPLE GALLERIES PER PAGE BUG

### ISSUE THREAD

**Issue by parusha22** [soflyy/oxygen-bugs-and-features#543]
When using more than one gallery on a page the light box works in the first gallery but is broken on any others - the lightbox pops up but the arrows are missing and there is no exit without using the back button.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**

*Yes

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**

YES

http://gleaming-petrel.w6.wpsandbox.pro/gallery-test/

**To Reproduce**
1. Go to first gallery - lightbox works
2. xxx
3. Scroll down to second gallery lightbox bugged

**Expected behavior**
*I expect to see light-box behave in gallery 2 same as gallery 1*

**What actually happens**
*lightbox in gallery 2 is missing scroll missing arrows and missing click to exit

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
 - Browser chrome
 - Oxygen Version 3.0

**Smartphone (please complete the following information):**
 - Oxygen Version [e.g. 2.2 Alpha]

**Additional context**
*Add any other context about the problem here.*

**Comment by KittenCodes** [comment]
Replicated internally.

**Comment by iakizz** [comment]
I would like to follow the resolution of this bug. I found the exact same issue, replicated here: http://jolly-hyena.w6.wpsandbox.pro/sample-page/

**Comment by woogonchung** [comment]
If this bug should stay for some time, what would be a workaround? 
I need to have multiple sections (of the gallery) displayed on a page. 
For example, I have three (3) groups of images. Those groups of thumbnails should be on a page and I want the lightbox feature.

**Comment by alriksson** [comment]
Also throwing js console errors. Doesn't matter if one two or more galleries are in use. the javascript error persists.

**Comment by alriksson** [comment]
No support for later jquery versions. Seems like the library do not even support jquery-3.4.1.min.js

**Comment by iakizz** [comment]
Hi,
FYI the issue has been fixed with latest releas of Oxygen 3.1, as you can see in their changelog: https://oxygenbuilder.com/2019/11/11/oxygen-3-1-now-available/

**Comment by parusha22** [comment]
Great that is good to know – it is not entirely clear how to update – do I download 3.1 again? Looks the same as the download I made in November With best wishes Mahesi From: iakizzSent: 04 December 2019 08:36To: soflyy/oxygen-bugs-and-featuresCc: parusha22; AuthorSubject: Re: [soflyy/oxygen-bugs-and-features] MULTIPLE GALLERIES PER PAGE BUG (#543) Hi,FYI the issue has been fixed with latest releas of Oxygen 3.1, as you can see in their changelog: https://oxygenbuilder.com/2019/11/11/oxygen-3-1-now-available/—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iakizz** [comment]
Hi @parusha22,
I can confirm that after upgrading my website to Oxygen 3.1, lightbox in multiple galleries work fine, as you can see here: https://iakizz.net/portfolio/

**Comment by parusha22** [comment]
You emailed me a while ago to tell me the multiple gallery bug had been fixed – meaning it should be possible to have two working galleries on the same page – where the light box has working scroll arrows to the side. I am disappointed to discover the bug is in fact NOT fixed – I am using Oxygen 3.1 Alpha 1 so it should be up to date.  Only the first gallery has a scroll – any other gallery that follows and is on the same page is missing the scroll That means the gallery helper is close to useless for me and a basic bug that is crying out to be fixed remains a show stopper... sad to say  With best wishes Mahesi From: iakizzSent: 04 December 2019 08:36To: soflyy/oxygen-bugs-and-featuresCc: parusha22; AuthorSubject: Re: [soflyy/oxygen-bugs-and-features] MULTIPLE GALLERIES PER PAGE BUG (#543) Hi,FYI the issue has been fixed with latest releas of Oxygen 3.1, as you can see in their changelog: https://oxygenbuilder.com/2019/11/11/oxygen-3-1-now-available/—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iakizz** [comment]
Hi @parusha22,
in my case after upgrading to Oxygen 3.1 the issue was solved. I think you could try downloading the latest stable version of Oxygen builder 3.1, not the alpha version.
In my case, it worked, as you can see in my portfolio gallery: https://iakizz.net/portfolio/

**Comment by parusha22** [comment]
Ok reverting back to 3.1 fixed it this – not sure why is would not have been in the newer version but there you go Thanks for your help With best wishes Mahesi From: iakizzSent: 09 January 2020 14:58To: soflyy/oxygen-bugs-and-featuresCc: parusha22; MentionSubject: Re: [soflyy/oxygen-bugs-and-features] MULTIPLE GALLERIES PER PAGE BUG (#543) Hi @parusha22,in my case after upgrading to Oxygen 3.1 the issue was solved. I think you could try downloading the latest stable version of Oxygen builder 3.1, not the alpha version.In my case, it worked, as you can see in my portfolio gallery: https://iakizz.net/portfolio/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by iakizz** [comment]
You're welcome. By the way, Oxygen 3.1 Alpha version is not newer than Oxygen 3.1, on the contrary it is a non-definitive trial version previous to the Beta.

**Comment by KittenCodes** [comment]
@parusha22 

> You're welcome. By the way, Oxygen 3.1 Alpha version is not newer than Oxygen 3.1, on the contrary it is a non-definitive trial version previous to the Beta.

This is correct. The release order is:

v3.1 Alpha
v3.1 Beta
v3.1 RC
v3.1 Stable (this is the current version)
