### ISSUE TITLE
Rich text element doesn't function correctly in Gutenberg

### ISSUE THREAD

**Issue by Martin-1** [soflyy/oxygen-bugs-and-features#545]
**Describe the bug**
The rich text element is empty when opened in Gutenberg

When I add a rich text element as a Gutenberg block and edit the page using Gutenberg, the rich text element doesn't function correctly. I see the text and can click on it, the rich text element opens in Gutenberg, but is empy. The original text is gone.
Also it is missing certain options like adding a link to the text or changing the text color.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://calm-flatworm.w5.wpsandbox.pro/

**To Reproduce**
1. Add a rich text element to the page using Oxygen.
2. Save it as a Gutenberg block
3. Edit the page in Gutenberg
4. Click the rich text element in Gutenberg

**Expected behavior**
I expected to at least see the original text and see the same options as in Oxygen (change the text, add links, color, font weight and so on).  This is what clients, who want to edit their own site, need.

**What actually happens**
The rich text element is empty and the text doesn't show up.

**Comment by busystreet** [comment]
This is almost required for end users to get the Tiny MCE like editing that they have been used to in WordPress classic editor.

**Comment by gitsimhub** [comment]
hopefully this will be fixed soon. #up

**Comment by Martin-1** [comment]
#up

**Comment by uzimike** [comment]
#up

**Comment by BL41N3Y** [comment]
#up

**Comment by KittenCodes** [comment]
This is fixed in the latest version of Oxygen (v3.1) and Gutenberg (v1.1). Please update to the latest versions from the customer portal here: https://oxygenbuilder.com/portal.

**Comment by BL41N3Y** [comment]
Thanks for the prompt reply.

I’ve just seen this in the 3.1 change log.

I’ve updated the Oxygen and Gutenberg through the installed plugins in WP (the licence keys hadn’t been attached on this site).

Having done so, I’m still not able to see the changes, see screenshot below:



I’ve cleared the cache, browser cache, Oxygen CSS cache and re-signed all shortcodes, logged out, logged back in and still no change.

Can you advise, also has the issue with the content not appearing in TinyMCE (as above) been fixed?

Thanks
Craig

**Comment by BL41N3Y** [comment]
All working now, thanks again.
