### ISSUE TITLE
Repeater not working properly when in Reusable

### ISSUE THREAD

**Issue by stitchinger** [soflyy/oxygen-bugs-and-features#625]
**Describe the bug**
Repeater which is in a Reusable can't be edited properly. Edior throws following error:

> Permalink not available for the current post/archive. If it is an archive for a custom post type , make sure that the parameter 'has_archive' for the post type is set to true.

The Repeater does get rendered on the frontend though.

**Have you tried all the steps at https://oxygenbuilder.com/documentation/troubleshooting/troubleshooting-guide/?**
No, bc I could reproduce the bug on the sandbox.

**Are you able to replicate the issue on a Sandbox install at https://oxygenbuilder.com/try?**
http://friendly-gaur.w6.wpsandbox.pro/?ct_template=test-resu&ct_builder=true

**To Reproduce**
1. Save a section with a repeater as a reusable.
2. Go to Oxygen > Templates
3. Open Reusable with Oxygenbuilder

**Expected behavior**
Repeater can be edited normally

**What actually happens**
- Repeater won't get rendered correctly in the builder, thus making it impossible to edit.
- Editor throws Error

**Screenshots**
<img width="292" alt="Bildschirmfoto 2019-10-13 um 01 55 53" src="https://user-images.githubusercontent.com/2757596/66709066-a014c280-ed5c-11e9-857d-50e0ac92ca20.png">

**Desktop (please complete the following information):**
- OS: MacOs Mojave
 - Browser Chrome
 - Oxygen Version 3.01

**Comment by KittenCodes** [comment]
This is fixed in Oxygen 3.1.

**Comment by johnfoll** [comment]
I am getting this same error. It may be related to the fact that I changed the slugs on one of my categories. I made sure that this category was not selected at the template level where this was used, but it still happens.

**Comment by tienthanh2929** [comment]
Still having errors, even after changing the permalink back and forth. I'm using fresh new WP and it still tells me the permalink not working.

**Comment by mdrumman** [comment]
Check the "All Archives"
![image](https://github.com/soflyy/oxygen-bugs-and-features/assets/14411225/597ccdf5-d117-4bb7-832a-db77e023cc2a)
